# Dockerfile
FROM python:3.9-slim-bullseye

ENV DISPLAY=${DISPLAY:-host.docker.internal:0.0}
ENV QT_X11_NO_MITSHM=1

RUN apt update -y && \
    apt install -y --no-install-recommends \
    vim \
    wget \
    openssh-client \
    git \
    python3-pip \
    libgl1-mesa-glx \
    python3-tk && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
    flask \
    requests \
    Pillow \
    matplotlib

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
